### ISSUE TITLE
[RFE] local-gadget: Add `--watch` option to the `list-containers` command

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#1028]
## Current situation

Currently, the `list-containers` command shows the containers currently running in the system. However, there is no option to know when a given container is created/deleted.

## Impact

It is not possible to debug the creation/deletion of containers using `local-gadget`.

## Ideal future situation

`local-gadget` should provide an option like `--watch` to trace the containers events:

```bash
$ sudo local-gadget list-containers --watch
TIME                 EVENT   RUNTIME    ID                                                               NAME
2022-10-10T18:33:04Z CREATED containerd 942ed1e839818822794247a5b3f55356c33cb72c6332fa66c008e4a99b3aec4e coredns
2022-10-10T18:33:04Z CREATED containerd c8a65cf1c8650cf25427774494d45f00f81b243e3842142d41d4417c7892fc0d etcd
2022-10-10T18:33:04Z CREATED containerd ac36877bb8acf26ebd5186d747b83d2c12304a5cbc16a73e09e6beebbc424960 gadget
2022-10-10T18:33:04Z CREATED containerd e03544daba437aecbe23efc4df791d9ee1c2a07a5a121f6d6686f33b70a56454 kindnet-cni
2022-10-10T18:33:04Z CREATED containerd eaeef87de99228e97f87f06bcec023d54242363cf11a22bb76a78acc193ddc78 kube-apiserver
2022-10-10T18:33:04Z CREATED containerd 598e2c3d1a58524c08a7c5e45c1b38424b7c2d03789528c85b313788e9904197 kube-controller-manager
2022-10-10T18:33:04Z CREATED containerd c18d844a8c0b57024205687595dc921ba99e9b2e0880a3f9dac6ee8afadf2949 kube-proxy
2022-10-10T18:33:04Z CREATED containerd 53d749a30929eb76b4a53857001431b5579d916101b507b05098ce6c79beee7e kube-scheduler
2022-10-10T18:33:04Z CREATED containerd f032e55c72bc0a88dd72fa6d17c0f5ead70037dd97b4462a0b85416e36b3ac16 storage-provisioner
# Create a container in another terminal
2022-10-10T18:34:00Z CREATED containerd b8e94b0e5297cb6d3f8a86b01c4fd8221628cadd9156036ca81e72accd95d01d myContainer
# Delete a container in another terminal
2022-10-10T18:35:02Z DELETED containerd b8e94b0e5297cb6d3f8a86b01c4fd8221628cadd9156036ca81e72accd95d01d myContainer
```

## Implementation options

```golang
diff --git a/cmd/local-gadget/containers/containers.go b/cmd/local-gadget/containers/containers.go
index 4dd645f7afce..3829cf808cd4 100644
--- a/cmd/local-gadget/containers/containers.go
+++ b/cmd/local-gadget/containers/containers.go
@@ -44,9 +44,20 @@ func NewListContainersCmd() *cobra.Command {
                                return commonutils.WrapInErrParserCreate(err)
                        }

-                       containers := localGadgetManager.GetContainersBySelector(&containercollection.ContainerSelector{
-                               Name: commonFlags.Containername,
-                       })
+                       containers := localGadgetManager.ContainerCollection.Subscribe(
+                               "local-gadget-key",
+                               containercollection.ContainerSelector{
+                                       Name: commonFlags.Containername,
+                               },
+                               func(event containercollection.PubSubEvent) {
+                                       switch event.Type {
+                                       case containercollection.EventTypeAddContainer:
+                                               // Print container created
+                                       case containercollection.EventTypeRemoveContainer:
+                                               // Print container deleted
+                                       }
+                               },
+                       )

                        parser.Sort(containers, []string{"runtime", "name"})

```

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/inspektor-gadget/inspektor-gadget/pull/1084.

**Comment by blanquicet** [comment]
Actually, there is still missing the delete event. So, I think this task should not be closed yet.

**Comment by mauriciovasquezbernal** [comment]
Right, reopening then
